#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
update_comments2.py - 更新dmsoft_impl.go的函数注释
"""

import re

# 参数描述映射
PARAM_DESC = {
    'hwnd': '窗口句柄',
    'x1': '左上角X坐标',
    'y1': '左上角Y坐标',
    'x2': '右下角X坐标',
    'y2': '右下角Y坐标',
    'x': 'X坐标',
    'y': 'Y坐标',
    'width': '宽度',
    'height': '高度',
    'w': '宽度',
    'h': '高度',
    'color': '颜色(格式: "RRGGBB-DRDGDB")',
    'sim': '相似度(0.1-1.0)',
    'dir': '查找方向(0:从左到右,1:从右到左,2:从上到下,3:从下到上)',
    'type': '类型',
    'type_': '类型',
    'mode': '模式',
    'index': '索引(从0开始)',
    'file': '文件路径',
    'path': '资源路径',
    'addr': '内存地址',
    'size': '大小(字节)',
    'len': '长度',
    'length': '长度',
    'data': '数据',
    'str': '要查找的字符串',
    'string': '字符串',
    'text': '文本内容',
    'name': '名称',
    'pic_name': '图片名称(多个用|分隔)',
    'pic_info': '图片信息',
    'delta_color': '颜色偏差',
    'offset_color': '偏移颜色',
    'first_color': '第一个颜色',
    'font_name': '字体名称',
    'font_size': '字体大小(像素)',
    'delay': '延迟时间(毫秒)',
    'timeout': '超时时间(毫秒)',
    'time_out': '超时时间(毫秒)',
    'time': '时间',
    'quality': '图片质量(1-100)',
    'en': '启用标志(1:启用,0:禁用)',
    'enable': '启用标志(1:启用,0:禁用)',
    'flag': '查找标志',
    'filter': '过滤条件',
    'sort': '排序方式',
    'step': '步长',
    'count': '数量',
    'multi_thread': '多线程数量',
    'request_type': '请求类型',
    'server': '服务器地址',
    'handle': '句柄',
    'code': '注册码',
    'ver': '版本号',
    'version': '版本号',
    'ip': 'IP地址',
    'pwd': '密码',
    'key': '键名',
    'value': '值',
    'v': '值',
    'section': 'INI节名',
    'cmd': '命令字符串',
    'command': '命令字符串',
    'current_dir': '当前目录',
    'url': 'URL地址',
    'save_file': '保存文件路径',
    'pic': '图片数据',
    'trans_color': '透明色',
    'objects': '检测到的对象',
    'prob': '概率阈值',
    'iou': 'IOU阈值',
    'base_addr': '模块基址',
    'fun_name': '函数名称',
    'module_name': '模块名称',
    'asm_code': '汇编代码字符串',
    'asm_ins': '汇编指令',
    'is_64bit': '是否64位',
    'float_value': '浮点数值',
    'double_value': '双精度浮点数值',
    'int_value': '整数值',
    'string_value': '字符串值',
    'float_value_min': '最小浮点值',
    'float_value_max': '最大浮点值',
    'double_value_min': '最小双精度值',
    'double_value_max': '最大双精度值',
    'int_value_min': '最小整数值',
    'int_value_max': '最大整数值',
    'addr_range': '地址范围',
    'process_name': '进程名称',
    'process_id': '进程ID',
    'pid': '进程ID',
    'class_name': '窗口类名',
    'title_name': '窗口标题',
    'title': '窗口标题',
    'parent': '父窗口句柄',
    'spec1': '条件1字符串',
    'spec2': '条件2字符串',
    'flag1': '条件1标志',
    'flag2': '条件2标志',
    'type1': '条件1类型',
    'type2': '条件2类型',
    'display': '显示模式',
    'mouse': '鼠标模式',
    'keypad': '键盘模式',
    'public_desc': '公共描述',
    'all_pos': '所有位置字符串',
    'msg': '消息内容',
    'info': '信息字符串',
    'param': '参数',
    'sub_cmd': '子命令',
    'rate': '速率',
    'fre': '频率(Hz)',
    'line_height': '行高(像素)',
    'col_gap': '列间距(像素)',
    'row_gap': '行间距(像素)',
    'word_gap': '字间距(像素)',
    'word': '要查找的文字',
    'dict_name': '字库文件名',
    'dict_info': '字库信息',
    'font_index': '字体索引',
    'exact_ocr': '精确OCR标志',
    'key_str': '按键字符串',
    'vk': '虚拟键码',
    'key_code': '键码',
    'rx': '相对X偏移',
    'ry': '相对Y偏移',
    'speed': '移动速度(1-100)',
    'lock': '锁定标志',
    'limit': '限制数量',
    't': '时间(毫秒)',
    'level': '级别',
    'uac': 'UAC标志',
    'over': '覆盖标志',
    'src_file': '源文件路径',
    'dst_file': '目标文件路径',
    'start_pos': '起始位置',
    'end_pos': '结束位置',
    'pmbi': '内存信息缓冲区指针',
    'old_protect': '旧保护属性指针',
    'mousedelay': '鼠标延迟(毫秒)',
    'mousestep': '鼠标步长',
    'id': '标识ID',
    'show': '显示标志(1:显示,0:隐藏)',
}

# 函数描述映射
FUNC_DESC = {
    'Init': '初始化大漠对象,创建内部对象实例',
    'Release': '释放大漠对象,销毁内部对象实例',
    'GetDiskReversion': '获取磁盘版本信息',
    'GetDiskSerial': '获取磁盘序列号',
    'GetDiskModel': '获取磁盘型号',
    'LoadAiMemory': '从内存加载AI模型',
    'LoadAi': '从文件加载AI模型',
    'FaqSend': '发送FAQ请求到服务器',
    'FaqGetSize': '获取FAQ数据大小',
    'FaqCapture': 'FAQ截图并保存到缓存',
    'FaqCaptureFromFile': '从文件加载图片到FAQ缓存',
    'FaqPost': '异步发送FAQ请求',
    'FaqIsPosted': '检查FAQ请求是否完成',
    'FaqCancel': '取消FAQ请求',
    'FaqCaptureString': '将字符串添加到FAQ缓存',
    'FaqFetch': '获取FAQ返回结果',
    'FindPic': '在指定区域查找图片',
    'FindPicEx': '高级查找图片,返回所有匹配位置',
    'FindPicE': '查找图片,返回坐标字符串',
    'FindPicS': '查找图片,返回图片索引',
    'FindPicSim': '查找图片相似度',
    'FindPicSimEx': '高级查找图片相似度',
    'FindPicSimMem': '在内存中查找图片(相似度模式)',
    'FindPicSimMemE': '在内存中查找图片,返回坐标字符串',
    'FindPicSimMemEx': '高级在内存中查找图片',
    'FindPicExS': '高级查找图片,返回详细字符串',
    'FindPicMem': '在内存中查找图片',
    'FindPicMemE': '在内存中查找图片,返回坐标字符串',
    'FindPicMemEx': '高级在内存中查找图片',
    'LoadPic': '预加载图片到内存',
    'LoadPicByte': '从字节数据加载图片到内存',
    'AiFindPic': '使用AI模型查找图片',
    'AiFindPicEx': 'AI高级查找图片',
    'AiFindPicMem': 'AI内存查找图片',
    'AiFindPicMemEx': 'AI高级内存查找图片',
    'AiEnableFindPicWindow': '启用AI找图窗口模式',
    'AiYoloSetVersion': '设置YOLO模型版本',
    'AiYoloSetModel': '从文件加载YOLO模型',
    'AiYoloSetModelMemory': '从内存加载YOLO模型',
    'AiYoloUseModel': '切换使用已加载的YOLO模型',
    'AiYoloDetectObjects': 'YOLO目标检测',
    'AiYoloDetectObjectsToFile': 'YOLO目标检测并保存到文件',
    'AiYoloDetectObjectsToDataBmp': 'YOLO目标检测到BMP数据',
    'AiYoloObjectsToString': 'YOLO检测结果转字符串',
    'AiYoloSortsObjects': 'YOLO检测结果排序',
    'AiYoloFreeModel': '释放YOLO模型',
    'Ver': '获取大漠插件版本号',
    'GetID': '获取大漠ID',
    'GetMachineCode': '获取机器码',
    'GetMachineCodeNoMac': '获取机器码(不含MAC地址)',
    'GetMac': '获取本机MAC地址',
    'Reg': '注册大漠插件',
    'RegEx': '扩展注册大漠插件',
    'RegNoMac': '注册大漠插件(不含MAC)',
    'RegExNoMac': '扩展注册大漠插件(不含MAC)',
    'GetLastError': '获取最后一次错误码',
    'SetPath': '设置资源文件路径',
    'GetPath': '获取当前资源路径',
    'GetBasePath': '获取大漠基础路径',
    'GetRealPath': '获取真实文件路径',
    'FindStrS': '查找文字,返回找到的文字字符串',
    'FindStr': '在指定区域查找文字',
    'FindStrEx': '高级查找文字,返回所有匹配位置',
    'FindStrExS': '高级查找文字,返回详细字符串',
    'FindStrFast': '快速查找文字',
    'FindStrFastE': '快速查找文字,返回坐标字符串',
    'FindStrFastEx': '高级快速查找文字',
    'FindStrFastS': '快速查找文字,返回字符串',
    'FindStrFastExS': '高级快速查找文字,返回详细字符串',
    'FindStrWithFont': '指定字体查找文字',
    'FindStrWithFontE': '指定字体查找文字,返回坐标字符串',
    'FindStrWithFontEx': '高级指定字体查找文字',
    'FindStrE': '查找文字,返回坐标字符串',
    'Ocr': 'OCR识别指定区域文字',
    'OcrEx': '高级OCR识别',
    'OcrExOne': 'OCR识别单个区域',
    'OcrInFile': '从图片文件进行OCR识别',
    'GetWords': '获取区域内的所有文字',
    'GetWordsNoDict': '无字典获取区域内的所有文字',
    'FetchWord': '提取文字',
    'GetWordResultCount': '获取文字识别结果数量',
    'GetWordResultPos': '获取文字识别结果位置',
    'GetWordResultStr': '获取文字识别结果字符串',
    'SetDict': '设置字库文件',
    'UseDict': '切换使用指定索引的字库',
    'AddDict': '添加字库条目',
    'ClearDict': '清除指定索引的字库',
    'SaveDict': '保存字库到文件',
    'GetDict': '获取字库内容',
    'GetDictCount': '获取字库条目数量',
    'GetNowDict': '获取当前使用的字库索引',
    'SetExportDict': '设置导出字库',
    'EnableShareDict': '启用共享字库',
    'SetDictMem': '从内存设置字库',
    'SetDictPwd': '设置字库密码',
    'GetDictInfo': '获取字库信息',
    'SetWordLineHeight': '设置文字识别行高',
    'SetWordLineHeightNoDict': '设置文字识别行高(无字典模式)',
    'SetMinColGap': '设置最小列间距',
    'SetColGapNoDict': '设置列间距(无字典模式)',
    'SetMinRowGap': '设置最小行间距',
    'SetRowGapNoDict': '设置行间距(无字典模式)',
    'SetWordGap': '设置字间距',
    'SetWordGapNoDict': '设置字间距(无字典模式)',
    'SetExactOcr': '设置精确OCR模式',
    'KeyPressChar': '按键(字符形式)',
    'KeyDownChar': '按下按键(字符形式)',
    'KeyUpChar': '弹起按键(字符形式)',
    'KeyPress': '按键(虚拟键码)',
    'KeyDown': '按下按键(虚拟键码)',
    'KeyUp': '弹起按键(虚拟键码)',
    'KeyPressStr': '按键字符串序列',
    'SetKeypadDelay': '设置键盘按键延迟',
    'SetSimMode': '设置模拟模式',
    'GetKeyState': '获取按键状态',
    'WaitKey': '等待按键',
    'MoveTo': '移动鼠标到指定坐标',
    'MoveR': '相对移动鼠标',
    'MoveToEx': '扩展移动鼠标,支持随机偏移',
    'MoveDD': 'DD驱动移动鼠标',
    'LeftClick': '鼠标左键单击',
    'LeftDown': '鼠标左键按下',
    'LeftUp': '鼠标左键弹起',
    'LeftDoubleClick': '鼠标左键双击',
    'RightClick': '鼠标右键单击',
    'RightDown': '鼠标右键按下',
    'RightUp': '鼠标右键弹起',
    'MiddleClick': '鼠标中键单击',
    'MiddleDown': '鼠标中键按下',
    'MiddleUp': '鼠标中键弹起',
    'WheelDown': '鼠标滚轮向下',
    'WheelUp': '鼠标滚轮向上',
    'GetCursorPos': '获取鼠标当前位置',
    'GetCursorShape': '获取鼠标形状',
    'GetCursorShapeEx': '获取鼠标形状(扩展)',
    'GetCursorSpot': '获取鼠标光点位置',
    'SetMouseSpeed': '设置鼠标移动速度',
    'GetMouseSpeed': '获取鼠标移动速度',
    'SetMouseDelay': '设置鼠标操作延迟',
    'LockMouseRect': '锁定鼠标移动区域',
    'EnableMouseMsg': '启用鼠标消息模拟',
    'EnableRealMouse': '启用真实鼠标模拟',
    'EnableMouseAccuracy': '启用鼠标精度',
    'GetColor': '获取指定坐标的颜色',
    'GetColorBGR': '获取指定坐标的BGR颜色',
    'GetColorHSV': '获取指定坐标的HSV颜色',
    'GetAveHSV': '获取区域平均HSV值',
    'CmpColor': '比较颜色',
    'FindColor': '在区域查找颜色',
    'FindColorE': '查找颜色,返回坐标字符串',
    'FindColorEx': '高级查找颜色',
    'FindColorBlock': '查找色块',
    'FindColorBlockEx': '高级查找色块',
    'GetColorNum': '获取区域中指定颜色的数量',
    'RGB2BGR': 'RGB颜色转BGR',
    'BGR2RGB': 'BGR颜色转RGB',
    'Capture': '截取屏幕区域',
    'CaptureGif': '截取屏幕区域为GIF',
    'CaptureJpg': '截取屏幕区域为JPG',
    'CapturePng': '截取屏幕区域为PNG',
    'GetScreenData': '获取屏幕数据',
    'GetScreenDataBmp': '获取屏幕BMP数据',
    'GetScreenWidth': '获取屏幕宽度',
    'GetScreenHeight': '获取屏幕高度',
    'GetScreenDepth': '获取屏幕色深',
    'GetDisplayInfo': '获取显示器信息',
    'SetScreen': '设置屏幕参数',
    'LockDisplay': '锁定显示区域',
    'SetDisplayInput': '设置显示输入方式',
    'SetDisplayDelay': '设置显示延迟',
    'SetDisplayRefreshDelay': '设置显示刷新延迟',
    'SetDisplayAcceler': '设置显示加速',
    'EnableGetColorByCapture': '启用截图取色模式',
    'IsDisplayDead': '检测屏幕是否死机',
    'BindWindow': '绑定窗口',
    'BindWindowEx': '扩展绑定窗口',
    'UnBindWindow': '解绑窗口',
    'ForceUnBindWindow': '强制解绑窗口',
    'SwitchBindWindow': '切换绑定窗口',
    'GetBindWindow': '获取绑定的窗口句柄',
    'IsBind': '判断是否已绑定窗口',
    'EnableBind': '启用/禁用绑定',
    'FindWindow': '查找窗口',
    'FindWindowEx': '扩展查找窗口',
    'FindWindowSuper': '超级查找窗口',
    'FindWindowByProcess': '通过进程名查找窗口',
    'FindWindowByProcessId': '通过进程ID查找窗口',
    'EnumWindow': '枚举窗口',
    'EnumWindowByProcess': '通过进程名枚举窗口',
    'EnumWindowByProcessId': '通过进程ID枚举窗口',
    'EnumWindowSuper': '超级枚举窗口',
    'GetWindow': '获取窗口',
    'GetWindowRect': '获取窗口矩形',
    'GetWindowClass': '获取窗口类名',
    'GetWindowTitle': '获取窗口标题',
    'SetWindowTitle': '设置窗口标题',
    'GetWindowState': '获取窗口状态',
    'SetWindowState': '设置窗口状态',
    'GetWindowProcessId': '获取窗口进程ID',
    'GetWindowThreadId': '获取窗口线程ID',
    'GetWindowProcessPath': '获取窗口进程路径',
    'GetForegroundWindow': '获取前台窗口',
    'GetForegroundFocus': '获取前台焦点窗口',
    'GetMousePointWindow': '获取鼠标指向的窗口',
    'GetPointWindow': '获取指定坐标的窗口',
    'ScreenToClient': '屏幕坐标转客户区坐标',
    'ClientToScreen': '客户区坐标转屏幕坐标',
    'SetWindowTransparent': '设置窗口透明度',
    'ShowTaskBarIcon': '显示/隐藏任务栏图标',
    'SetEnumWindowDelay': '设置枚举窗口延迟',
    'MoveWindow': '移动窗口',
    'SetWindowSize': '设置窗口大小',
    'GetClientRect': '获取客户区矩形',
    'GetClientSize': '获取客户区大小',
    'ReadInt': '读取整数',
    'ReadIntAddr': '读取整数(指定地址)',
    'WriteInt': '写入整数',
    'WriteIntAddr': '写入整数(指定地址)',
    'ReadFloat': '读取浮点数',
    'ReadFloatAddr': '读取浮点数(指定地址)',
    'WriteFloat': '写入浮点数',
    'WriteFloatAddr': '写入浮点数(指定地址)',
    'ReadDouble': '读取双精度浮点数',
    'ReadDoubleAddr': '读取双精度浮点数(指定地址)',
    'WriteDouble': '写入双精度浮点数',
    'WriteDoubleAddr': '写入双精度浮点数(指定地址)',
    'ReadString': '读取字符串',
    'ReadStringAddr': '读取字符串(指定地址)',
    'WriteString': '写入字符串',
    'WriteStringAddr': '写入字符串(指定地址)',
    'ReadData': '读取数据',
    'ReadDataAddr': '读取数据(指定地址)',
    'ReadDataToBin': '读取数据到二进制',
    'ReadDataAddrToBin': '读取数据到二进制(指定地址)',
    'WriteData': '写入数据',
    'WriteDataAddr': '写入数据(指定地址)',
    'WriteDataFromBin': '从二进制写入数据',
    'WriteDataAddrFromBin': '从二进制写入数据(指定地址)',
    'FindData': '查找数据',
    'FindDataEx': '高级查找数据',
    'FindInt': '查找整数',
    'FindIntEx': '高级查找整数',
    'FindFloat': '查找浮点数',
    'FindFloatEx': '高级查找浮点数',
    'FindDouble': '查找双精度浮点数',
    'FindDoubleEx': '高级查找双精度浮点数',
    'FindString': '查找字符串',
    'FindStringEx': '高级查找字符串',
    'VirtualAllocEx': '在目标进程分配内存',
    'VirtualProtectEx': '修改目标进程内存保护属性',
    'VirtualQueryEx': '查询目标进程内存信息',
    'GetModuleBaseAddr': '获取模块基址',
    'GetModuleSize': '获取模块大小',
    'GetRemoteApiAddress': '获取远程API地址',
    'OpenProcess': '打开进程',
    'TerminateProcess': '终止进程',
    'TerminateProcessTree': '终止进程树',
    'FreeProcessMemory': '释放进程内存',
    'GetMemoryUsage': '获取内存使用情况',
    'SetMemoryHwndAsProcessId': '设置内存操作使用进程ID',
    'SetMemoryFindResultToFile': '设置内存查找结果输出到文件',
    'AsmAdd': '添加汇编指令',
    'AsmClear': '清除汇编代码',
    'AsmCall': '调用汇编代码',
    'AsmCallEx': '扩展调用汇编代码',
    'AsmSetTimeout': '设置汇编执行超时',
    'DisAssemble': '反汇编',
    'SetShowAsmErrorMsg': '设置是否显示汇编错误信息',
    'ReadFile': '读取文件内容',
    'ReadFileData': '读取文件数据',
    'WriteFile': '写入文件',
    'CopyFile': '复制文件',
    'MoveFile': '移动文件',
    'DeleteFile': '删除文件',
    'IsFileExist': '判断文件是否存在',
    'GetFileLength': '获取文件长度',
    'CreateFolder': '创建文件夹',
    'DeleteFolder': '删除文件夹',
    'IsFolderExist': '判断文件夹是否存在',
    'SelectFile': '选择文件对话框',
    'SelectDirectory': '选择目录对话框',
    'GetDir': '获取特殊目录路径',
    'EncodeFile': '加密文件',
    'DecodeFile': '解密文件',
    'ImageToBmp': '图片转换为BMP格式',
    'DownloadFile': '下载文件',
    'ReadIni': '读取INI配置',
    'ReadIniPwd': '读取INI配置(带密码)',
    'WriteIni': '写入INI配置',
    'WriteIniPwd': '写入INI配置(带密码)',
    'DeleteIni': '删除INI配置项',
    'DeleteIniPwd': '删除INI配置项(带密码)',
    'EnumIniKey': '枚举INI键',
    'EnumIniKeyPwd': '枚举INI键(带密码)',
    'EnumIniSection': '枚举INI节',
    'EnumIniSectionPwd': '枚举INI节(带密码)',
    'GetOsType': '获取操作系统类型',
    'GetOsBuildNumber': '获取操作系统版本号',
    'GetTime': '获取系统时间',
    'GetNetTime': '获取网络时间',
    'GetNetTimeSafe': '安全获取网络时间',
    'GetCpuType': '获取CPU类型',
    'GetCpuUsage': '获取CPU使用率',
    'GetDPI': '获取系统DPI',
    'Is64Bit': '判断是否64位系统',
    'IsSurrpotVt': '判断是否支持VT虚拟化',
    'CheckUAC': '检查UAC状态',
    'SetUAC': '设置UAC状态',
    'GetSystemInfo': '获取系统信息',
    'GetCommandLine': '获取命令行',
    'ExitOs': '退出系统',
    'SetLocale': '设置区域',
    'GetLocale': '获取区域',
    'DisableScreenSave': '禁用屏保',
    'DisablePowerSave': '禁用节能模式',
    'DisableCloseDisplayAndSleep': '禁用关闭显示器和睡眠',
    'DownCpu': '降低CPU使用率',
    'EnumProcess': '枚举进程',
    'GetProcessInfo': '获取进程信息',
    'CreateFoobarRect': '创建矩形Foobar窗口',
    'CreateFoobarEllipse': '创建椭圆Foobar窗口',
    'CreateFoobarRoundRect': '创建圆角矩形Foobar窗口',
    'CreateFoobarCustom': '创建自定义Foobar窗口',
    'FoobarClose': '关闭Foobar窗口',
    'FoobarFillRect': 'Foobar填充矩形',
    'FoobarDrawText': 'Foobar绘制文字',
    'FoobarDrawPic': 'Foobar绘制图片',
    'FoobarDrawLine': 'Foobar绘制线条',
    'FoobarLock': '锁定Foobar窗口',
    'FoobarUnlock': '解锁Foobar窗口',
    'FoobarUpdate': '更新Foobar窗口',
    'FoobarSetSave': '设置Foobar保存',
    'FoobarSetTrans': '设置Foobar透明度',
    'FoobarSetFont': '设置Foobar字体',
    'FoobarTextRect': '设置Foobar文字区域',
    'FoobarTextLineGap': '设置Foobar文字行间距',
    'FoobarTextPrintDir': '设置Foobar文字打印方向',
    'FoobarPrintText': 'Foobar打印文字',
    'FoobarClearText': 'Foobar清除文字',
    'FoobarStartGif': 'Foobar开始播放GIF',
    'FoobarStopGif': 'Foobar停止播放GIF',
    'FindMultiColor': '多点找色',
    'FindMultiColorEx': '高级多点找色',
    'FindShape': '查找形状',
    'FindShapeE': '查找形状,返回坐标字符串',
    'FindShapeEx': '高级查找形状',
    'SetParam64ToPointer': '设置64位参数转指针',
    'SetFindPicMultithreadCount': '设置找图多线程数量',
    'SetFindPicMultithreadLimit': '设置找图多线程限制',
    'EnableFindPicMultithread': '启用找图多线程',
    'SetExcludeRegion': '设置排除区域',
    'EnablePicCache': '启用图片缓存',
    'MatchPicName': '匹配图片名称',
    'AppendPicAddr': '追加图片地址',
    'FindNearestPos': '查找最近位置',
    'SortPosDistance': '按距离排序位置',
    'ExcludePos': '排除位置',
    'Delay': '延迟指定时间',
    'Delays': '随机延迟',
    'Play': '播放声音文件',
    'Beep': '蜂鸣器',
    'SetClipboard': '设置剪贴板内容',
    'GetClipboard': '获取剪贴板内容',
    'SendString': '发送字符串',
    'SendString2': '发送字符串2',
    'SendStringIme': '通过输入法发送字符串',
    'SendStringIme2': '通过输入法发送字符串2',
    'SendPaste': '发送粘贴',
    'ActiveInputMethod': '激活输入法',
    'CheckInputMethod': '检查输入法状态',
    'FindInputMethod': '查找输入法',
    'EnableIme': '启用输入法',
    'LockInput': '锁定输入',
    'EnableKeypadSync': '启用键盘同步',
    'EnableKeypadMsg': '启用键盘消息',
    'EnableKeypadPatch': '启用键盘补丁',
    'EnableRealKeypad': '启用真实键盘',
    'EnableFakeActive': '启用假激活',
    'EnableSpeedDx': '启用速度DX',
    'SpeedNormalGraphic': '速度正常图形',
    'SetAero': '设置Aero效果',
    'SetExitThread': '设置退出线程',
    'DmGuard': '大漠守护',
    'DmGuardParams': '大漠守护参数',
    'DmGuardLoadCustom': '大漠守护加载自定义模块',
    'DmGuardExtract': '大漠守护解压',
    'UnLoadDriver': '卸载驱动',
    'HackSpeed': '加速',
    'RunApp': '运行程序',
    'ExecuteCmd': '执行命令',
    'Md5': '计算MD5值',
    'Hex64': '64位整数转十六进制字符串',
    'Hex32': '32位整数转十六进制字符串',
    'IntToData': '整数转数据',
    'FloatToData': '浮点数转数据',
    'DoubleToData': '双精度转数据',
    'StringToData': '字符串转数据',
    'Int64ToInt32': 'int64转int32',
    'GetFps': '获取FPS',
    'SetInputDm': '设置输入大漠',
    'GetDmCount': '获取大漠对象计数',
    'ReleaseRef': '释放引用',
    'Stop': '停止',
    'EnterCri': '进入临界区',
    'LeaveCri': '离开临界区',
    'InitCri': '初始化临界区',
    'CheckFontSmooth': '检查字体平滑',
    'EnableFontSmooth': '启用字体平滑',
    'DisableFontSmooth': '禁用字体平滑',
    'SetShowErrorMsg': '设置是否显示错误信息',
    'EnableDisplayDebug': '启用显示调试',
    'ShowScrMsg': '显示屏幕消息',
}

def get_param_desc(param_name, param_type):
    """获取参数描述"""
    if param_type.startswith('*'):
        base_desc = PARAM_DESC.get(param_name, param_name)
        return f'{base_desc}(输出参数)'
    return PARAM_DESC.get(param_name, param_name)

def parse_params(params_str):
    """解析参数字符串"""
    params = []
    if not params_str.strip():
        return params
    
    for param in params_str.split(','):
        param = param.strip()
        if not param:
            continue
        words = param.split()
        if len(words) >= 2:
            param_type = words[-1]
            param_names = words[:-1]
            for name in param_names:
                if name and name != '*':
                    params.append((param_type, name))
    return params

def generate_comment(func_name, params, return_type):
    """生成函数注释"""
    desc = FUNC_DESC.get(func_name, func_name)
    lines = [f'// {func_name} {desc}']
    
    for param_type, param_name in params:
        param_desc = get_param_desc(param_name, param_type)
        lines.append(f'// 参数: {param_name} - {param_desc}')
    
    if return_type:
        if return_type == 'int32':
            lines.append('// 返回: 成功返回1,失败返回0')
        elif return_type == 'string':
            lines.append('// 返回: 结果字符串')
        elif return_type == 'int64':
            lines.append('// 返回: 64位整数值')
        elif return_type == 'float32':
            lines.append('// 返回: 32位浮点数')
        elif return_type == 'float64':
            lines.append('// 返回: 64位浮点数')
        elif return_type == 'bool':
            lines.append('// 返回: 布尔值')
    
    return '\n'.join(lines)

def update_comments(file_path):
    """更新Go文件注释"""
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    new_lines = []
    i = 0
    while i < len(lines):
        line = lines[i]
        
        # 检测函数定义
        match = re.match(r'^func \(\*?dm \*DmSoftImpl\) (\w+)\(([^)]*)\)(\s*\([^)]*\)|\s*\w+)?\s*\{', line)
        if match:
            func_name = match.group(1)
            params_str = match.group(2)
            return_type = match.group(3).strip() if match.group(3) else ''
            
            # 跳过已有的注释
            comment_lines = []
            j = i - 1
            while j >= 0 and lines[j].strip().startswith('//'):
                comment_lines.insert(0, lines[j])
                j -= 1
            
            # 生成新注释
            params = parse_params(params_str)
            new_comment = generate_comment(func_name, params, return_type)
            
            # 添加新注释
            new_lines.append(new_comment + '\n')
            new_lines.append(line)
        else:
            new_lines.append(line)
        
        i += 1
    
    with open(file_path, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)
    
    print("注释更新完成")

if __name__ == '__main__':
    file_path = r'E:\SRC\dm\72424_C++\go\dmsoft_impl.go'
    update_comments(file_path)
