#ifndef __INCLUDE_OBJ_H__
#define __INCLUDE_OBJ_H__

#if !defined(__cplusplus)
#error C++ compiler required
#endif
#include <atlstr.h>
// 正常加载和卸载插件
DWORD LoadDm(PCSTR path);
BOOL FreeDm(void);

class dmsoft
{
private:
    long obj;

public:
    dmsoft();
    virtual ~dmsoft();

    virtual CString GetDiskReversion(long index);
    virtual long LoadAiMemory(long addr,long size);
    virtual CString FaqSend(PCSTR server,long handle,long request_type,long time_out);
    virtual long FindPicSimMem(long x1,long y1,long x2,long y2,PCSTR pic_info,PCSTR delta_color,long sim,long dir,long* x,long* y);
    virtual CString Ver();
    virtual long SetPath(PCSTR path);
    virtual long SetShowAsmErrorMsg(long show);
    virtual CString FindStrS(long x1,long y1,long x2,long y2,PCSTR str,PCSTR color,double sim,long* x,long* y);
    virtual CString GetWordsNoDict(long x1,long y1,long x2,long y2,PCSTR color);
    virtual long GetOsBuildNumber();
    virtual long GetID();
    virtual long SetMouseSpeed(long speed);
    virtual CString FindData(long hwnd,PCSTR addr_range,PCSTR data);
    virtual long SendPaste(long hwnd);
    virtual CString GetColor(long x,long y);
    virtual long LoadPicByte(long addr,long size,PCSTR name);
    virtual long WriteFloatAddr(long hwnd,LONGLONG addr,float float_value);
    virtual long SetWordLineHeight(long line_height);
    virtual LONGLONG AsmCall(long hwnd,long mode);
    virtual long FindColorBlock(long x1,long y1,long x2,long y2,PCSTR color,double sim,long count,long width,long height,long* x,long* y);
    virtual CString DisAssemble(PCSTR asm_code,LONGLONG base_addr,long is_64bit);
    virtual long RegEx(PCSTR code,PCSTR ver,PCSTR ip);
    virtual long EncodeFile(PCSTR file,PCSTR pwd);
    virtual long WriteString(long hwnd,PCSTR addr,long type,PCSTR v);
    virtual CString FindStrFastEx(long x1,long y1,long x2,long y2,PCSTR str,PCSTR color,double sim);
    virtual LONGLONG AsmCallEx(long hwnd,long mode,PCSTR base_addr);
    virtual CString FindDoubleEx(long hwnd,PCSTR addr_range,double double_value_min,double double_value_max,long step,long multi_thread,long mode);
    virtual long SetFindPicMultithreadLimit(long limit);
    virtual long SendString2(long hwnd,PCSTR str);
    virtual long DownCpu(long type,long rate);
    virtual long DmGuard(long enable,PCSTR type);
    virtual long SpeedNormalGraphic(long en);
    virtual long FindPicSim(long x1,long y1,long x2,long y2,PCSTR pic_name,PCSTR delta_color,long sim,long dir,long* x,long* y);
    virtual long WriteInt(long hwnd,PCSTR addr,long type,LONGLONG v);
    virtual long SetMemoryHwndAsProcessId(long en);
    virtual long WriteDataFromBin(long hwnd,PCSTR addr,long data,long len);
    virtual long SetMinColGap(long col_gap);
    virtual long KeyPressStr(PCSTR key_str,long delay);
    virtual long LockDisplay(long lock);
    virtual CString FindStrWithFontE(long x1,long y1,long x2,long y2,PCSTR str,PCSTR color,double sim,PCSTR font_name,long font_size,long flag);
    virtual CString EnumIniKey(PCSTR section,PCSTR file);
    virtual CString MatchPicName(PCSTR pic_name);
    virtual long EnableFakeActive(long en);
    virtual long FaqGetSize(long handle);
    virtual CString ExecuteCmd(PCSTR cmd,PCSTR current_dir,long time_out);
    virtual long EnableRealKeypad(long en);
    virtual long SetDisplayRefreshDelay(long t);
    virtual long MiddleClick();
    virtual CString AiYoloSortsObjects(PCSTR objects,long height);
    virtual long WriteDataAddr(long hwnd,LONGLONG addr,PCSTR data);
    virtual CString RGB2BGR(PCSTR rgb_color);
    virtual long DisablePowerSave();
    virtual long GetClientSize(long hwnd,long* width,long* height);
    virtual long EnableMouseMsg(long en);
    virtual long EnableKeypadMsg(long en);
    virtual long GetFileLength(PCSTR file);
    virtual LONGLONG GetRemoteApiAddress(long hwnd,LONGLONG base_addr,PCSTR fun_name);
    virtual CString DmGuardParams(PCSTR cmd,PCSTR sub_cmd,PCSTR param);
    virtual long DownloadFile(PCSTR url,PCSTR save_file,long timeout);
    virtual long WriteDoubleAddr(long hwnd,LONGLONG addr,double double_value);
    virtual long EnableIme(long en);
    virtual long TerminateProcessTree(long pid);
    virtual long FoobarClose(long hwnd);
    virtual CString FindNearestPos(PCSTR all_pos,long type,long x,long y);
    virtual long CreateFoobarRect(long hwnd,long x,long y,long w,long h);
    virtual long GetCursorPos(long* x,long* y);
    virtual CString FindColorBlockEx(long x1,long y1,long x2,long y2,PCSTR color,double sim,long count,long width,long height);
    virtual CString FindFloat(long hwnd,PCSTR addr_range,float float_value_min,float float_value_max);
    virtual CString GetProcessInfo(long pid);
    virtual CString ReadFile(PCSTR file);
    virtual CString FindShapeEx(long x1,long y1,long x2,long y2,PCSTR offset_color,double sim,long dir);
    virtual long SetWindowText(long hwnd,PCSTR text);
    virtual long ForceUnBindWindow(long hwnd);
    virtual LONGLONG ReadIntAddr(long hwnd,LONGLONG addr,long type);
    virtual long FindShape(long x1,long y1,long x2,long y2,PCSTR offset_color,double sim,long dir,long* x,long* y);
    virtual CString GetRealPath(PCSTR path);
    virtual long EnableSpeedDx(long en);
    virtual long UnLoadDriver();
    virtual long GetMemoryUsage();
    virtual long MiddleDown();
    virtual CString EnumIniSection(PCSTR file);
    virtual long CheckUAC();
    virtual long OpenProcess(long pid);
    virtual long IsDisplayDead(long x1,long y1,long x2,long y2,long t);
    virtual long WriteIniPwd(PCSTR section,PCSTR key,PCSTR v,PCSTR file,PCSTR pwd);
    virtual CString GetNetTime();
    virtual float ReadFloat(long hwnd,PCSTR addr);
    virtual long DisableCloseDisplayAndSleep();
    virtual CString GetWindowTitle(long hwnd);
    virtual CString Assemble(LONGLONG base_addr,long is_64bit);
    virtual long GetMousePointWindow();
    virtual long SetExportDict(long index,PCSTR dict_name);
    virtual long Delay(long mis);
    virtual long Reg(PCSTR code,PCSTR ver);
    virtual long FoobarStopGif(long hwnd,long x,long y,PCSTR pic_name);
    virtual CString ReadFileData(PCSTR file,long start_pos,long end_pos);
    virtual CString FindPicSimEx(long x1,long y1,long x2,long y2,PCSTR pic_name,PCSTR delta_color,long sim,long dir);
    virtual long Capture(long x1,long y1,long x2,long y2,PCSTR file);
    virtual long GetScreenWidth();
    virtual CString FindStrWithFontEx(long x1,long y1,long x2,long y2,PCSTR str,PCSTR color,double sim,PCSTR font_name,long font_size,long flag);
    virtual long SetLocale();
    virtual long AsmAdd(PCSTR asm_ins);
    virtual long GetScreenHeight();
    virtual long CaptureGif(long x1,long y1,long x2,long y2,PCSTR file,long delay,long time);
    virtual long ReadDataAddrToBin(long hwnd,LONGLONG addr,long len);
    virtual long ReadDataToBin(long hwnd,PCSTR addr,long len);
    virtual CString FindPicS(long x1,long y1,long x2,long y2,PCSTR pic_name,PCSTR delta_color,double sim,long dir,long* x,long* y);
    virtual long FindPic(long x1,long y1,long x2,long y2,PCSTR pic_name,PCSTR delta_color,double sim,long dir,long* x,long* y);
    virtual long FindMultiColor(long x1,long y1,long x2,long y2,PCSTR first_color,PCSTR offset_color,double sim,long dir,long* x,long* y);
    virtual long HackSpeed(double rate);
    virtual CString FindPicE(long x1,long y1,long x2,long y2,PCSTR pic_name,PCSTR delta_color,double sim,long dir);
    virtual long MiddleUp();
    virtual long GetWindow(long hwnd,long flag);
    virtual long SetUAC(long uac);
    virtual long FoobarSetSave(long hwnd,PCSTR file,long en,PCSTR header);
    virtual long WheelDown();
    virtual CString FloatToData(float float_value);
    virtual long EnableFindPicMultithread(long en);
    virtual long DisableScreenSave();
    virtual CString AiFindPicEx(long x1,long y1,long x2,long y2,PCSTR pic_name,double sim,long dir);
    virtual long SendString(long hwnd,PCSTR str);
    virtual long EnterCri();
    virtual CString FindPicSimMemE(long x1,long y1,long x2,long y2,PCSTR pic_info,PCSTR delta_color,long sim,long dir);
    virtual long Delays(long min_s,long max_s);
    virtual long CreateFoobarCustom(long hwnd,long x,long y,PCSTR pic,PCSTR trans_color,double sim);
    virtual CString FindStringEx(long hwnd,PCSTR addr_range,PCSTR string_value,long type,long step,long multi_thread,long mode);
    virtual long GetClientRect(long hwnd,long* x1,long* y1,long* x2,long* y2);
    virtual long AiYoloSetModel(long index,PCSTR file,PCSTR pwd);
    virtual long FoobarSetTrans(long hwnd,long trans,PCSTR color,double sim);
    virtual long GetForegroundFocus();
    virtual long GetForegroundWindow();
    virtual long SetExcludeRegion(long type,PCSTR info);
    virtual long SendStringIme2(long hwnd,PCSTR str,long mode);
    virtual long ActiveInputMethod(long hwnd,PCSTR id);
    virtual long FoobarDrawPic(long hwnd,long x,long y,PCSTR pic,PCSTR trans_color);
    virtual long AiYoloSetVersion(PCSTR ver);
    virtual CString FindColorE(long x1,long y1,long x2,long y2,PCSTR color,double sim,long dir);
    virtual long LeftClick();
    virtual long IsFileExist(PCSTR file);
    virtual long Is64Bit();
    virtual CString FindShapeE(long x1,long y1,long x2,long y2,PCSTR offset_color,double sim,long dir);
    virtual CString GetDisplayInfo();
    virtual long SetEnumWindowDelay(long delay);
    virtual long RegNoMac(PCSTR code,PCSTR ver);
    virtual long KeyUpChar(PCSTR key_str);
    virtual long SetDisplayAcceler(long level);
    virtual long SetRowGapNoDict(long row_gap);
    virtual long EnableMouseAccuracy(long en);
    virtual long MoveTo(long x,long y);
    virtual long KeyPressChar(PCSTR key_str);
    virtual long RightDown();
    virtual long AiYoloSetModelMemory(long index,long addr,long size,PCSTR pwd);
    virtual long WriteIni(PCSTR section,PCSTR key,PCSTR v,PCSTR file);
    virtual long DmGuardLoadCustom(PCSTR type,PCSTR path);
    virtual long CreateFolder(PCSTR folder_name);
    virtual long EnableRealMouse(long en,long mousedelay,long mousestep);
    virtual CString GetBasePath();
    virtual long GetFps();
    virtual long EnableGetColorByCapture(long enable);
    virtual long SetDisplayInput(PCSTR mode);
    virtual CString Hex64(LONGLONG v);
    virtual long ScreenToClient(long hwnd,long* x,long* y);
    virtual long AiEnableFindPicWindow(long enable);
    virtual CString ReadIni(PCSTR section,PCSTR key,PCSTR file);
    virtual long ImageToBmp(PCSTR pic_name,PCSTR bmp_name);
    virtual long SetDisplayDelay(long t);
    virtual long WheelUp();
    virtual long CopyFile(PCSTR src_file,PCSTR dst_file,long over);
    virtual long FindWindowEx(long parent,PCSTR class_name,PCSTR title_name);
    virtual long SetFindPicMultithreadCount(long count);
    virtual long GetScreenDataBmp(long x1,long y1,long x2,long y2,long* data,long* size);
    virtual long GetWordResultPos(PCSTR str,long index,long* x,long* y);
    virtual long LeftDoubleClick();
    virtual CString ReadStringAddr(long hwnd,LONGLONG addr,long type,long len);
    virtual CString ReadData(long hwnd,PCSTR addr,long len);
    virtual long AddDict(long index,PCSTR dict_info);
    virtual long SetInputDm(long input_dm,long rx,long ry);
    virtual long GetWindowProcessId(long hwnd);
    virtual long WriteDataAddrFromBin(long hwnd,LONGLONG addr,long data,long len);
    virtual CString AiFindPicMemEx(long x1,long y1,long x2,long y2,PCSTR pic_info,double sim,long dir);
    virtual long TerminateProcess(long pid);
    virtual CString VirtualQueryEx(long hwnd,LONGLONG addr,long pmbi);
    virtual long EnableKeypadSync(long enable,long time_out);
    virtual long AiYoloUseModel(long index);
    virtual long DeleteFile(PCSTR file);
    virtual long GetScreenDepth();
    virtual long FindColor(long x1,long y1,long x2,long y2,PCSTR color,double sim,long dir,long* x,long* y);
    virtual long MoveR(long rx,long ry);
    virtual long LockInput(long lock);
    virtual CString IntToData(LONGLONG int_value,long type);
    virtual long FaqPost(PCSTR server,long handle,long request_type,long time_out);
    virtual CString GetColorHSV(long x,long y);
    virtual long FindWindowSuper(PCSTR spec1,long flag1,long type1,PCSTR spec2,long flag2,long type2);
    virtual long EnableBind(long en);
    virtual long SetAero(long enable);
    virtual long DecodeFile(PCSTR file,PCSTR pwd);
    virtual CString FindPicExS(long x1,long y1,long x2,long y2,PCSTR pic_name,PCSTR delta_color,double sim,long dir);
    virtual long WriteStringAddr(long hwnd,LONGLONG addr,long type,PCSTR v);
    virtual CString GetCommandLine(long hwnd);
    virtual CString SelectFile();
    virtual CString FindPicSimMemEx(long x1,long y1,long x2,long y2,PCSTR pic_info,PCSTR delta_color,long sim,long dir);
    virtual CString GetWordResultStr(PCSTR str,long index);
    virtual long EnablePicCache(long en);
    virtual CString FindStrExS(long x1,long y1,long x2,long y2,PCSTR str,PCSTR color,double sim);
    virtual long LoadPic(PCSTR pic_name);
    virtual long FindStrFast(long x1,long y1,long x2,long y2,PCSTR str,PCSTR color,double sim,long* x,long* y);
    virtual CString FindDouble(long hwnd,PCSTR addr_range,double double_value_min,double double_value_max);
    virtual long SetParam64ToPointer();
    virtual long SetMemoryFindResultToFile(PCSTR file);
    virtual long WaitKey(long key_code,long time_out);
    virtual long CreateFoobarEllipse(long hwnd,long x,long y,long w,long h);
    virtual long MoveFile(PCSTR src_file,PCSTR dst_file);
    virtual long Stop(long id);
    virtual long ReleaseRef();
    virtual CString GetColorBGR(long x,long y);
    virtual CString EnumIniKeyPwd(PCSTR section,PCSTR file,PCSTR pwd);
    virtual CString GetMac();
    virtual long UseDict(long index);
    virtual CString FindDataEx(long hwnd,PCSTR addr_range,PCSTR data,long step,long multi_thread,long mode);
    virtual CString Md5(PCSTR str);
    virtual CString BGR2RGB(PCSTR bgr_color);
    virtual CString FindColorEx(long x1,long y1,long x2,long y2,PCSTR color,double sim,long dir);
    virtual CString OcrExOne(long x1,long y1,long x2,long y2,PCSTR color,double sim);
    virtual long CmpColor(long x,long y,PCSTR color,double sim);
    virtual CString OcrInFile(long x1,long y1,long x2,long y2,PCSTR pic_name,PCSTR color,double sim);
    virtual long CheckInputMethod(long hwnd,PCSTR id);
    virtual long MoveWindow(long hwnd,long x,long y);
    virtual CString GetClipboard();
    virtual long FindStr(long x1,long y1,long x2,long y2,PCSTR str,PCSTR color,double sim,long* x,long* y);
    virtual long FoobarClearText(long hwnd);
    virtual long ClientToScreen(long hwnd,long* x,long* y);
    virtual CString GetCursorShape();
    virtual long GetWordResultCount(PCSTR str);
    virtual CString SelectDirectory();
    virtual long CapturePng(long x1,long y1,long x2,long y2,PCSTR file);
    virtual long KeyDownChar(PCSTR key_str);
    virtual long CaptureJpg(long x1,long y1,long x2,long y2,PCSTR file,long quality);
    virtual CString FindStrEx(long x1,long y1,long x2,long y2,PCSTR str,PCSTR color,double sim);
    virtual long FaqCapture(long x1,long y1,long x2,long y2,long quality,long delay,long time);
    virtual long ShowScrMsg(long x1,long y1,long x2,long y2,PCSTR msg,PCSTR color);
    virtual long SetKeypadDelay(PCSTR type,long delay);
    virtual long SetScreen(long width,long height,long depth);
    virtual long Play(PCSTR file);
    virtual long FindWindowByProcessId(long process_id,PCSTR class_name,PCSTR title_name);
    virtual long WriteDouble(long hwnd,PCSTR addr,double double_value);
    virtual long GetWindowThreadId(long hwnd);
    virtual long GetBindWindow();
    virtual long FindWindow(PCSTR class_name,PCSTR title_name);
    virtual long AiFindPic(long x1,long y1,long x2,long y2,PCSTR pic_name,double sim,long dir,long* x,long* y);
    virtual CString FindInt(long hwnd,PCSTR addr_range,LONGLONG int_value_min,LONGLONG int_value_max,long type);
    virtual long IsBind(long hwnd);
    virtual long SetSimMode(long mode);
    virtual long GetNowDict();
    virtual CString GetNetTimeSafe();
    virtual CString GetMachineCode();
    virtual LONGLONG VirtualAllocEx(long hwnd,LONGLONG addr,long size,long type);
    virtual CString GetPath();
    virtual CString EnumWindowSuper(PCSTR spec1,long flag1,long type1,PCSTR spec2,long flag2,long type2,long sort);
    virtual LONGLONG GetModuleBaseAddr(long hwnd,PCSTR module_name);
    virtual CString EnumWindowByProcessId(long pid,PCSTR title,PCSTR class_name,long filter);
    virtual long UnBindWindow();
    virtual long GetLastError();
    virtual long FoobarDrawText(long hwnd,long x,long y,long w,long h,PCSTR text,PCSTR color,long align);
    virtual long SetMinRowGap(long row_gap);
    virtual long LeftUp();
    virtual long WriteFile(PCSTR file,PCSTR content);
    virtual long SetWindowSize(long hwnd,long width,long height);
    virtual long FaqCaptureFromFile(long x1,long y1,long x2,long y2,PCSTR file,long quality);
    virtual CString ReadDataAddr(long hwnd,LONGLONG addr,long len);
    virtual long IsSurrpotVt();
    virtual CString GetWindowProcessPath(long hwnd);
    virtual long ClearDict(long index);
    virtual long SaveDict(long index,PCSTR file);
    virtual long ShowTaskBarIcon(long hwnd,long is_show);
    virtual CString GetAveHSV(long x1,long y1,long x2,long y2);
    virtual CString ReadIniPwd(PCSTR section,PCSTR key,PCSTR file,PCSTR pwd);
    virtual long FaqIsPosted();
    virtual long LeftDown();
    virtual long DmGuardExtract(PCSTR type,PCSTR path);
    virtual long ExitOs(long type);
    virtual CString FetchWord(long x1,long y1,long x2,long y2,PCSTR color,PCSTR word);
    virtual CString GetDiskSerial(long index);
    virtual long GetDictCount(long index);
    virtual CString GetDict(long index,long font_index);
    virtual long SetDict(long index,PCSTR dict_name);
    virtual CString AiYoloObjectsToString(PCSTR objects);
    virtual long GetKeyState(long vk);
    virtual long RightClick();
    virtual CString EnumWindowByProcess(PCSTR process_name,PCSTR title,PCSTR class_name,long filter);
    virtual CString GetDiskModel(long index);
    virtual long SendStringIme(PCSTR str);
    virtual CString AppendPicAddr(PCSTR pic_info,long addr,long size);
    virtual long DeleteFolder(PCSTR folder_name);
    virtual long GetDPI();
    virtual long GetCpuType();
    virtual long WriteIntAddr(long hwnd,LONGLONG addr,long type,LONGLONG v);
    virtual long GetSpecialWindow(long flag);
    virtual CString EnumProcess(PCSTR name);
    virtual long AsmClear();
    virtual long GetWindowState(long hwnd,long flag);
    virtual CString FindStrFastE(long x1,long y1,long x2,long y2,PCSTR str,PCSTR color,double sim);
    virtual long SetColGapNoDict(long col_gap);
    virtual CString AiYoloDetectObjects(long x1,long y1,long x2,long y2,float prob,float iou);
    virtual long RunApp(PCSTR path,long mode);
    virtual CString FindString(long hwnd,PCSTR addr_range,PCSTR string_value,long type);
    virtual long GetOsType();
    virtual CString Ocr(long x1,long y1,long x2,long y2,PCSTR color,double sim);
    virtual CString ReadString(long hwnd,PCSTR addr,long type,long len);
    virtual float ReadFloatAddr(long hwnd,LONGLONG addr);
    virtual long Beep(long fre,long delay);
    virtual long LoadAi(PCSTR file);
    virtual long GetCpuUsage();
    virtual long EnableShareDict(long en);
    virtual long AiYoloDetectObjectsToFile(long x1,long y1,long x2,long y2,float prob,float iou,PCSTR file,long mode);
    virtual long FoobarUnlock(long hwnd);
    virtual CString GetSystemInfo(PCSTR type,long method);
    virtual long GetResultCount(PCSTR str);
    virtual CString EnumWindow(long parent,PCSTR title,PCSTR class_name,long filter);
    virtual long GetResultPos(PCSTR str,long index,long* x,long* y);
    virtual long KeyDown(long vk);
    virtual long SetWordLineHeightNoDict(long line_height);
    virtual long AiFindPicMem(long x1,long y1,long x2,long y2,PCSTR pic_info,double sim,long dir,long* x,long* y);
    virtual long FoobarTextRect(long hwnd,long x,long y,long w,long h);
    virtual long GetPointWindow(long x,long y);
    virtual CString FindMultiColorEx(long x1,long y1,long x2,long y2,PCSTR first_color,PCSTR offset_color,double sim,long dir);
    virtual long FreeProcessMemory(long hwnd);
    virtual CString GetMachineCodeNoMac();
    virtual long FindWindowByProcess(PCSTR process_name,PCSTR class_name,PCSTR title_name);
    virtual long SetWindowState(long hwnd,long flag);
    virtual long CheckFontSmooth();
    virtual long IsFolderExist(PCSTR folder);
    virtual long FaqCancel();
    virtual long SetWindowTransparent(long hwnd,long v);
    virtual long SwitchBindWindow(long hwnd);
    virtual long EnableFontSmooth();
    virtual CString StringToData(PCSTR string_value,long type);
    virtual long GetWindowRect(long hwnd,long* x1,long* y1,long* x2,long* y2);
    virtual CString FindPicEx(long x1,long y1,long x2,long y2,PCSTR pic_name,PCSTR delta_color,double sim,long dir);
    virtual CString GetWords(long x1,long y1,long x2,long y2,PCSTR color,double sim);
    virtual long SetExactOcr(long exact_ocr);
    virtual long EnableMouseSync(long enable,long time_out);
    virtual long CapturePre(PCSTR file);
    virtual long BindWindowEx(long hwnd,PCSTR display,PCSTR mouse,PCSTR keypad,PCSTR public_desc,long mode);
    virtual long FaqCaptureString(PCSTR str);
    virtual long FoobarTextLineGap(long hwnd,long gap);
    virtual long FoobarDrawLine(long hwnd,long x1,long y1,long x2,long y2,PCSTR color,long style,long width);
    virtual long FindInputMethod(PCSTR id);
    virtual long SetPicPwd(PCSTR pwd);
    virtual CString GetCursorSpot();
    virtual long InitCri();
    virtual CString FindPicMemE(long x1,long y1,long x2,long y2,PCSTR pic_info,PCSTR delta_color,double sim,long dir);
    virtual CString FindStrFastS(long x1,long y1,long x2,long y2,PCSTR str,PCSTR color,double sim,long* x,long* y);
    virtual long DeleteIniPwd(PCSTR section,PCSTR key,PCSTR file,PCSTR pwd);
    virtual long GetColorNum(long x1,long y1,long x2,long y2,PCSTR color,double sim);
    virtual long AiYoloDetectObjectsToDataBmp(long x1,long y1,long x2,long y2,float prob,float iou,long* data,long* size,long mode);
    virtual long AiYoloFreeModel(long index);
    virtual long DisableFontSmooth();
    virtual long SetExitThread(long mode);
    virtual CString FindPicMemEx(long x1,long y1,long x2,long y2,PCSTR pic_info,PCSTR delta_color,double sim,long dir);
    virtual long GetDmCount();
    virtual long FindMulColor(long x1,long y1,long x2,long y2,PCSTR color,double sim);
    virtual CString FaqFetch();
    virtual long RegExNoMac(PCSTR code,PCSTR ver,PCSTR ip);
    virtual long FoobarUpdate(long hwnd);
    virtual double ReadDouble(long hwnd,PCSTR addr);
    virtual CString GetCursorShapeEx(long type);
    virtual CString DoubleToData(double double_value);
    virtual long SetWordGapNoDict(long word_gap);
    virtual double ReadDoubleAddr(long hwnd,LONGLONG addr);
    virtual long FoobarLock(long hwnd);
    virtual CString FindStrFastExS(long x1,long y1,long x2,long y2,PCSTR str,PCSTR color,double sim);
    virtual long FindStrWithFont(long x1,long y1,long x2,long y2,PCSTR str,PCSTR color,double sim,PCSTR font_name,long font_size,long flag,long* x,long* y);
    virtual long VirtualProtectEx(long hwnd,LONGLONG addr,long size,long type,long old_protect);
    virtual CString GetWindowClass(long hwnd);
    virtual long SetMouseDelay(PCSTR type,long delay);
    virtual LONGLONG ReadInt(long hwnd,PCSTR addr,long type);
    virtual CString GetAveRGB(long x1,long y1,long x2,long y2);
    virtual long GetScreenData(long x1,long y1,long x2,long y2);
    virtual long GetMouseSpeed();
    virtual long Int64ToInt32(LONGLONG v);
    virtual CString FindFloatEx(long hwnd,PCSTR addr_range,float float_value_min,float float_value_max,long step,long multi_thread,long mode);
    virtual long FoobarPrintText(long hwnd,PCSTR text,PCSTR color);
    virtual CString OcrEx(long x1,long y1,long x2,long y2,PCSTR color,double sim);
    virtual long FreePic(PCSTR pic_name);
    virtual long WriteData(long hwnd,PCSTR addr,PCSTR data);
    virtual long MoveDD(long dx,long dy);
    virtual long SetShowErrorMsg(long show);
    virtual long SetDictMem(long index,long addr,long size);
    virtual long SetClipboard(PCSTR data);
    virtual long FindPicMem(long x1,long y1,long x2,long y2,PCSTR pic_info,PCSTR delta_color,double sim,long dir,long* x,long* y);
    virtual long CreateFoobarRoundRect(long hwnd,long x,long y,long w,long h,long rw,long rh);
    virtual long WriteFloat(long hwnd,PCSTR addr,float float_value);
    virtual long VirtualFreeEx(long hwnd,LONGLONG addr);
    virtual CString GetDictInfo(PCSTR str,PCSTR font_name,long font_size,long flag);
    virtual long KeyPress(long vk);
    virtual long SetClientSize(long hwnd,long width,long height);
    virtual CString ExcludePos(PCSTR all_pos,long type,long x1,long y1,long x2,long y2);
    virtual CString MoveToEx(long x,long y,long w,long h);
    virtual long SetDictPwd(PCSTR pwd);
    virtual long FoobarSetFont(long hwnd,PCSTR font_name,long size,long flag);
    virtual CString GetNetTimeByIp(PCSTR ip);
    virtual long EnableKeypadPatch(long enable);
    virtual long FoobarStartGif(long hwnd,long x,long y,PCSTR pic_name,long repeat_limit,long delay);
    virtual CString FindMultiColorE(long x1,long y1,long x2,long y2,PCSTR first_color,PCSTR offset_color,double sim,long dir);
    virtual long SetWordGap(long word_gap);
    virtual long GetLocale();
    virtual long GetModuleSize(long hwnd,PCSTR module_name);
    virtual CString FindStrE(long x1,long y1,long x2,long y2,PCSTR str,PCSTR color,double sim);
    virtual long KeyUp(long vk);
    virtual CString SortPosDistance(PCSTR all_pos,long type,long x,long y);
    virtual long EnableDisplayDebug(long enable_debug);
    virtual long DeleteIni(PCSTR section,PCSTR key,PCSTR file);
    virtual CString FindIntEx(long hwnd,PCSTR addr_range,LONGLONG int_value_min,LONGLONG int_value_max,long type,long step,long multi_thread,long mode);
    virtual long BindWindow(long hwnd,PCSTR display,PCSTR mouse,PCSTR keypad,long mode);
    virtual CString GetPicSize(PCSTR pic_name);
    virtual long AsmSetTimeout(long time_out,long param);
    virtual long LockMouseRect(long x1,long y1,long x2,long y2);
    virtual CString FindPicSimE(long x1,long y1,long x2,long y2,PCSTR pic_name,PCSTR delta_color,long sim,long dir);
    virtual CString EnumIniSectionPwd(PCSTR file,PCSTR pwd);
    virtual long RightUp();
    virtual long FoobarTextPrintDir(long hwnd,long dir);
    virtual CString GetDir(long type);
    virtual CString Hex32(long v);
    virtual long LeaveCri();
    virtual long GetTime();
    virtual long FoobarFillRect(long hwnd,long x1,long y1,long x2,long y2,PCSTR color);
};

#endif
